# Generated by Django 3.0.2 on 2020-02-19 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flagstone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shuttle',
            name='departure_dropoff',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shuttle',
            name='departure_pickup_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shuttle',
            name='departure_pickup_location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shuttle',
            name='departure_pickup_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shuttle',
            name='primary_dropoff',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shuttle',
            name='primary_pickup_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shuttle',
            name='primary_pickup_location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shuttle',
            name='primary_pickup_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
