# Generated by Django 3.0.2 on 2020-02-19 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flagstone', '0002_auto_20200219_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='shuttle',
            name='arrival_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shuttle',
            name='departing_ground_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shuttle',
            name='departing_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shuttle',
            name='primary_ground_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shuttle',
            name='arrival_airline',
            field=models.CharField(blank=True, choices=[('Advanced Air', 'Advanced Air'), ('Air Canada', 'Air Canada'), ('Alaska Airlines', 'Alaska Airlines'), ('Allegiant', 'Allegiant'), ('American Airlines', 'American Airlines'), ('Boutique Air', 'Boutique Air'), ('British Airways', 'British Airways'), ('Condor Airlines', 'Condor Airlines'), ('Contour Airlines', 'Contour Airlines'), ('Delta Air Lines', 'Delta Air Lines'), ('Eurowings', 'Eurowings'), ('Frontier Airlines', 'Frontier Airlines'), ('Hawaiian Airlines', 'Hawaiian Airlines'), ('JetBlue Airways', 'JetBlue Airways'), ('JSX-Swift Aviation', 'JSX-Swift Aviation'), ('Southwest Airlines', 'Southwest Airlines'), ('Spirit Airlines', 'Spirit Airlines'), ('Sun Country Airlines', 'Sun Country Airlines'), ('United Airlines', 'United Airlines'), ('Volaris', 'Volaris'), ('WestJet', 'WestJet'), ('Other', 'Other')], max_length=25),
        ),
        migrations.AlterField(
            model_name='shuttle',
            name='arrival_airport',
            field=models.CharField(blank=True, choices=[('TIA', 'Tucson'), ('SKY', 'SkyHarbor')], default='TIA', max_length=9),
        ),
        migrations.AlterField(
            model_name='shuttle',
            name='arrival_flight',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='shuttle',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=55.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='shuttle',
            name='customer_info',
            field=models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.DO_NOTHING, to='flagstone.Customer'),
        ),
        migrations.AlterField(
            model_name='shuttle',
            name='departure_airline',
            field=models.CharField(blank=True, choices=[('Advanced Air', 'Advanced Air'), ('Air Canada', 'Air Canada'), ('Alaska Airlines', 'Alaska Airlines'), ('Allegiant', 'Allegiant'), ('American Airlines', 'American Airlines'), ('Boutique Air', 'Boutique Air'), ('British Airways', 'British Airways'), ('Condor Airlines', 'Condor Airlines'), ('Contour Airlines', 'Contour Airlines'), ('Delta Air Lines', 'Delta Air Lines'), ('Eurowings', 'Eurowings'), ('Frontier Airlines', 'Frontier Airlines'), ('Hawaiian Airlines', 'Hawaiian Airlines'), ('JetBlue Airways', 'JetBlue Airways'), ('JSX-Swift Aviation', 'JSX-Swift Aviation'), ('Southwest Airlines', 'Southwest Airlines'), ('Spirit Airlines', 'Spirit Airlines'), ('Sun Country Airlines', 'Sun Country Airlines'), ('United Airlines', 'United Airlines'), ('Volaris', 'Volaris'), ('WestJet', 'WestJet'), ('Other', 'Other')], max_length=25),
        ),
        migrations.AlterField(
            model_name='shuttle',
            name='departure_airport',
            field=models.CharField(blank=True, choices=[('TIA', 'Tucson'), ('SKY', 'SkyHarbor')], default='Tucson', max_length=9),
        ),
        migrations.AlterField(
            model_name='shuttle',
            name='departure_flight',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='shuttle',
            name='event_name',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AlterField(
            model_name='shuttle',
            name='org_name',
            field=models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.DO_NOTHING, to='flagstone.Organization'),
        ),
    ]
