# Generated by Django 3.0.2 on 2020-02-20 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flagstone', '0005_shuttle_status_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuttle',
            name='customer_info',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='flagstone.Customer'),
        ),
        migrations.AlterField(
            model_name='shuttle',
            name='event_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='shuttle',
            name='org_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='flagstone.Organization'),
        ),
    ]
