# Generated by Django 3.0.2 on 2020-02-25 18:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flagstone', '0006_auto_20200220_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='rental_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='return_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='time_returned',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='affiliate_info',
            field=models.ForeignKey(default='Self', on_delete=django.db.models.deletion.DO_NOTHING, to='flagstone.Organization'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='additional_driver_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='rental',
            name='hitch_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='rental',
            name='luggage_rack_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='rental',
            name='mexico_insurance_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
