# Generated by Django 3.0.2 on 2020-02-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flagstone', '0007_auto_20200225_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='return_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='rental',
            name='time_returned',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shuttle',
            name='payment_status',
            field=models.CharField(choices=[('PAID IN FULL', 'PAID IN FULL'), ('PAYMENT DUE', 'PAYMENT DUE'), ('DELINQUENT', 'DELINQUENT')], default='PAYMENT DUE', max_length=25),
        ),
    ]
