# Generated by Django 3.0.2 on 2020-02-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flagstone', '0010_auto_20200227_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='praasa_march2020',
            name='total_due_status',
            field=models.CharField(choices=[('PAID IN FULL', 'PAID IN FULL'), ('PAYMENT DUE', 'PAYMENT DUE'), ('DELINQUENT', 'DELINQUENT')], default='PAYMENT DUE', max_length=56),
        ),
        migrations.AlterField(
            model_name='praasa_march2020',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=5),
        ),
    ]
