# Generated by Django 3.0.2 on 2020-02-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flagstone', '0012_auto_20200227_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praasa_march2020',
            name='drop_location',
            field=models.CharField(blank=True, default='Westin La Paloma', max_length=256),
        ),
    ]
