# Generated by Django 3.0.2 on 2020-02-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flagstone', '0015_auto_20200227_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praasa_march2020',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='praasa_march2020',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='praasa_march2020',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='praasa_march2020',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='praasa_march2020',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='praasa_march2020',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
