# Generated by Django 3.0.2 on 2020-02-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flagstone', '0017_auto_20200227_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='date_returned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='return_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='time_returned',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
