# Generated by Django 3.0.2 on 2020-03-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flagstone', '0018_auto_20200228_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praasa_march2020',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
