# Generated by Django 3.0.2 on 2020-03-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flagstone', '0020_auto_20200302_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='praasa_march2020',
            name='shuttle_type',
            field=models.CharField(choices=[('Round Trip', 'Round Trip'), ('One Way', 'One Way')], default='Round Trip', max_length=56),
        ),
    ]
