# Generated by Django 3.0.2 on 2020-03-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flagstone', '0021_praasa_march2020_shuttle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praasa_march2020',
            name='arrival_airline',
            field=models.CharField(blank=True, choices=[('Alaska Airlines', 'Alaska Airlines'), ('Allegiant', 'Allegiant'), ('American Airlines', 'American Airlines'), ('Delta Air Lines', 'Delta Air Lines'), ('Eurowings', 'Eurowings'), ('Frontier Airlines', 'Frontier Airlines'), ('Southwest Airlines', 'Southwest Airlines'), ('Sun Country Airlines', 'Sun Country Airlines'), ('United Airlines', 'United Airlines'), ('Other', 'Other')], max_length=25),
        ),
        migrations.AlterField(
            model_name='praasa_march2020',
            name='departure_airline',
            field=models.CharField(blank=True, choices=[('Alaska Airlines', 'Alaska Airlines'), ('Allegiant', 'Allegiant'), ('American Airlines', 'American Airlines'), ('Delta Air Lines', 'Delta Air Lines'), ('Eurowings', 'Eurowings'), ('Frontier Airlines', 'Frontier Airlines'), ('Southwest Airlines', 'Southwest Airlines'), ('Sun Country Airlines', 'Sun Country Airlines'), ('United Airlines', 'United Airlines'), ('Other', 'Other')], max_length=25),
        ),
    ]
