# Generated by Django 3.0.2 on 2020-03-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flagstone', '0025_auto_20200303_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='praasa_march2020',
            name='status_box',
            field=models.CharField(choices=[('Arrived', 'Arrived'), ('Return Trip', 'Return Trip'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=56),
        ),
    ]
