# Generated by Django 3.0.2 on 2020-03-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flagstone', '0030_auto_20200311_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercarf',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
        ),
    ]
