# Generated by Django 3.0.2 on 2022-01-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flagstone', '0031_customercarf_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customercarf',
            options={'ordering': ['arrival_time']},
        ),
        migrations.AlterField(
            model_name='customercarf',
            name='arrival_date',
            field=models.DateField(blank=True, default='2020-03-20', null=True),
        ),
        migrations.AlterField(
            model_name='customercarf',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=55.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='customercarf',
            name='departure_date',
            field=models.DateField(blank=True, default='2020-03-22', null=True),
        ),
        migrations.AlterField(
            model_name='customercarf',
            name='email',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='customercarf',
            name='phone',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='customercarf',
            name='reservation_status',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('Cancelled', 'Cancelled'), ('Paid-Self', 'Paid-Self'), ('Paid-Other', 'Paid-Other')], default='Reserved', max_length=28),
        ),
        migrations.AlterField(
            model_name='customercarf',
            name='reservation_type',
            field=models.CharField(choices=[('One Way Arrival', 'One Way Arrival'), ('One Way Departure', 'One Way Departure'), ('Round Trip', 'Round Trip')], default='Round Trip', max_length=28),
        ),
    ]
